### ISSUE TITLE
TODO: somehow impliment starting Access-point

### ISSUE THREAD

**Issue by bsimjoo-official** [bsimjoo-official/kian#1]
I don't know how I ment to do so, but I think it's better to impliment methods to open the access point (hotspot).
In first beta version I used windows cmd command `netsh wlan start ...` and it works very well but there are some issues.

first user should run `main.py` and it will use flask development server that is not perfect! and second
it works only on windows. Here are my ideas right now:
 - write a luncher using python or batch/bash that opens Access point first and then run server using a configuration
 - just left it as it is!
 - write doc that users should first open a hotspot with some commands and then run the app!

I'm just opening an issue for myself in future as a note right now, but I will be so happy, if someone reading this issue,
and I will rejoice if somebody replies to it!

**Comment by farooqkz** [comment]
You can use Github milestones instead of creating a `v1` label, my friend :)
